# properties
# k=v

# 对空格的要求十分高

# 可以注入到我们的配置类中

# 普通的 key value
#name: kobe
#
## 对象
#student:
#  name: kobe
#  age: 3
#
#
## 行内写法
#student2: {name: kobe, age: 3}
#
#
## 数组
#pets:
#  - cat
#  - dog
#  - pig
#
#pets2: [cat,dog,pig]


person:
  name: kobe${random.uuid}
  age: ${random.int}
  happy: false
  birth: 2020/1/28
  maps: {k1: v1,k2: v2}
  hello: 常威
  lists:
    - basketball
    - coach
    - music
  dog:
    name: ${person.hello:hello}_旺财
    age: 3